#!/usr/bin/perl

use strict;
use CGI 'param','header';
use Net::SMTP;

my %rate = ( 1=>'从不', 2=> '偶尔', 3=>'经常', 4=>'频繁' );

my $q;
my ( $key, $value );

$q = new CGI;
print $q->header( -type=>'text/html',
		-charset=>'utf-8' );

open( FD, "<../../header.html" );
print <FD>;
close( FD );
print <<_HTML_;
<table width="760" cellspacing="0" cellpadding="0">
  <tr> 
    <td width="550" valign="top" rowspan="2"> 
      <table width="500" cellspacing="0" cellpadding="0" align="center">
        <tr> 
          <td valign="top"> 
            <p><br>
              <b><font color="#3366CC">您的位置：</font></b><a href="/" class="a5">阿卡首页</a> 
              <font color="#458DE4">&gt;</font> <a href="/customer/order/index.shtml" class="a5">定购</a> 
              <font color="#458DE4">&gt;</font> <span class="a5">VPN服务</span></p>
            <p class="newstitle">购买VPN服务</p>
            <p>
